sudo: required
services:
  - docker

script:
  - echo "Build xgo-base image"
  - cd ./docker/base/
  - docker build -t "xgo-base" .
  - cd ../go-1.7.1/
  - docker build -t "xgo-1.7.1" .
  - echo "List all image"
  - docker images
  - cd ./
  - echo "Build go example hello-world"
  - go get github.com/golang/example/hello
  - go build github.com/golang/example/hello
  - ./hello
  - echo "Get xgo"  
  - go get github.com/nguoianphu/xgo
  - echo "Build code with xgo"
  - xgo -go 1.7.1 github.com/golang/example/hello
  - ls -la
