sudo: required
services:
  - docker

script:
  - echo "Build xgo-base image"
  - cd ./docker/base/
  - docker build -t "xgo-base" .
  - cd ../go-1.7.1/
  - docker build -t "xgo-1.7.1" .
  - echo "List all image"
  - docker images
  - cd ./
  - go get github.com/nguoianphu/xgo
  - echo "Build golang"
  - xgo github.com/project-iris/iris
