# Go cross compiler (xgo): Wildcard layer to the latest Go release
# Copyright (c) 2014 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM tsg/xgo-1.4.x

MAINTAINER Péter Szilágyi <peterke@gmail.com>
